# Generated by Django 2.1.3 on 2018-11-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='votes',
            field=models.IntegerField(null=True),
        ),
    ]
