# Generated by Django 2.1.3 on 2018-11-26 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20181126_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeplan',
            old_name='mael_name',
            new_name='meal_name',
        ),
    ]
