
# Generated by Django 2.0.3 on 2018-11-28 09:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20181126_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(default='Sposob przygotowania'),

            preserve_default=False,
        ),
    ]
